export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const ADD_DATA_SUCCESS = 'ADD_DATA_SUCCESS';
export const UPDATE_DATA_SUCCESS = 'UPDATE_DATA_SUCCESS';
export const DELETE_DATA_SUCCESS = 'DELETE_DATA_SUCCESS';
export const FETCH_SINGLE_DATA_SUCCESS = 'FETCH_SINGLE_DATA_SUCCESS';
